### ISSUE TITLE
[问题咨询] | UCSVQE 这个 lib 是用来干什么的呢？

### ISSUE THREAD

**Issue by dannyZhou** [vintonliu/SoundTouchDemo#1]
您好，我在阅读您的源代码的时候，发现，UCSVQE 这个 lib.jar 这个 jar 存在的意义是什么，主要起到什么样的作用呢？

**Comment by wenchang85** [comment]
这是一个第三方的音频增强处理库，比如回声抑制，噪音消除、自动增益等
